import { createTheme, DefaultTheme } from '@reportforge/theme';

export const MinimalTheme = createTheme(
  'minimal',
  {
    colors: {
      primary: '#111111',
      secondary: '#666666',
      background: '#ffffff',
      surface: '#ffffff',
      border: '#e5e5e5',
      textPrimary: '#111111',
      textSecondary: '#666666',
      muted: '#999999',
      text: '#111111',
      textMuted: '#999999',
    },
    components: {
      title: { color: 'textPrimary', fontSize: 'xl', fontWeight: 600 },
      subtitle: { color: 'textPrimary', fontSize: 'lg', fontWeight: 600 },
      heading: { color: 'textPrimary', fontSize: 'lg', fontWeight: 600 },
      paragraph: { color: 'textSecondary', fontSize: 'md' },
      caption: { color: 'muted', fontSize: 'sm' },
      label: { color: 'textSecondary', fontSize: 'sm' },
      table: { fontSize: 'sm' },
      header: { background: 'background' },
      footer: { background: 'background', color: 'muted' },
      summaryCard: { background: 'surface', color: 'textPrimary' },
      metricCard: { background: 'surface' },
      divider: { borderColor: 'border' },
      section: {},
    },
  },
  DefaultTheme,
);

export const CorporateTheme = createTheme(
  'corporate',
  {
    colors: {
      primary: '#003366',
      secondary: '#0055aa',
      accent: '#0066cc',
      background: '#ffffff',
      surface: '#f0f4f8',
      border: '#c5d0dc',
      textPrimary: '#1a2332',
      textSecondary: '#4a5568',
      muted: '#718096',
      text: '#1a2332',
      textMuted: '#718096',
      success: '#047857',
    },
    typography: {
      fontFamily: 'Helvetica',
      fontSizeTitle: 26,
      fontSizeSubtitle: 20,
    },
    components: {
      title: { color: 'primary', fontSize: '2xl', fontWeight: 700 },
      subtitle: { color: 'primary', fontSize: 'xl', fontWeight: 700 },
      heading: { color: 'primary', fontSize: 'lg', fontWeight: 700 },
      paragraph: { color: 'textPrimary', fontSize: 'md' },
      caption: { color: 'muted', fontSize: 'sm' },
      label: { color: 'textSecondary', fontSize: 'sm', fontWeight: 600 },
      table: { fontSize: 'sm' },
      header: { background: 'surface', color: 'primary' },
      footer: { background: 'surface', color: 'muted', fontSize: 'sm' },
      summaryCard: { background: 'surface', color: 'primary' },
      metricCard: { background: 'surface', color: 'textPrimary' },
      divider: { borderColor: 'border' },
      section: {},
    },
  },
  DefaultTheme,
);

export const DarkTheme = createTheme(
  'dark',
  {
    colors: {
      primary: '#60a5fa',
      secondary: '#94a3b8',
      accent: '#38bdf8',
      background: '#0f172a',
      surface: '#1e293b',
      border: '#334155',
      textPrimary: '#f1f5f9',
      textSecondary: '#cbd5e1',
      muted: '#94a3b8',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
      success: '#34d399',
      warning: '#fbbf24',
      danger: '#f87171',
      error: '#f87171',
    },
    components: {
      title: { color: 'textPrimary', fontSize: '2xl', fontWeight: 700 },
      subtitle: { color: 'textPrimary', fontSize: 'xl', fontWeight: 600 },
      heading: { color: 'textPrimary', fontSize: 'lg', fontWeight: 600 },
      paragraph: { color: 'textSecondary', fontSize: 'md' },
      caption: { color: 'muted', fontSize: 'sm' },
      label: { color: 'textSecondary', fontSize: 'sm' },
      table: { fontSize: 'sm' },
      header: { background: 'surface', color: 'textPrimary' },
      footer: { background: 'surface', color: 'muted' },
      summaryCard: { background: 'surface', color: 'primary' },
      metricCard: { background: 'surface' },
      divider: { borderColor: 'border' },
      section: {},
    },
    page: { background: 'background' },
  },
  DefaultTheme,
);

export const HealthcareTheme = createTheme(
  'healthcare',
  {
    colors: {
      primary: '#0891b2',
      secondary: '#06b6d4',
      accent: '#22d3ee',
      background: '#ffffff',
      surface: '#ecfeff',
      border: '#a5f3fc',
      textPrimary: '#164e63',
      textSecondary: '#155e75',
      muted: '#67e8f9',
      text: '#164e63',
      textMuted: '#0891b2',
      success: '#059669',
      info: '#0284c7',
    },
    components: {
      title: { color: 'primary', fontSize: '2xl', fontWeight: 700 },
      subtitle: { color: 'primary', fontSize: 'xl', fontWeight: 600 },
      heading: { color: 'textPrimary', fontSize: 'lg', fontWeight: 600 },
      paragraph: { color: 'textPrimary', fontSize: 'md' },
      caption: { color: 'muted', fontSize: 'sm' },
      label: { color: 'textSecondary', fontSize: 'sm' },
      table: { fontSize: 'sm' },
      header: { background: 'surface', color: 'primary' },
      footer: { background: 'surface', color: 'textSecondary' },
      summaryCard: { background: 'surface', color: 'primary' },
      metricCard: { background: 'surface' },
      divider: { borderColor: 'border' },
      section: {},
    },
  },
  DefaultTheme,
);

export const FinancialTheme = createTheme(
  'financial',
  {
    colors: {
      primary: '#1e3a5f',
      secondary: '#2d5986',
      accent: '#c9a227',
      background: '#ffffff',
      surface: '#f5f7fa',
      border: '#d1d9e6',
      textPrimary: '#1a2332',
      textSecondary: '#4a5568',
      muted: '#718096',
      text: '#1a2332',
      textMuted: '#718096',
      success: '#059669',
      danger: '#b91c1c',
      error: '#b91c1c',
    },
    typography: {
      fontFamily: 'Times-Roman',
      fontSizeTitle: 26,
    },
    components: {
      title: { color: 'primary', fontSize: '2xl', fontWeight: 700 },
      subtitle: { color: 'primary', fontSize: 'xl', fontWeight: 700 },
      heading: { color: 'primary', fontSize: 'lg', fontWeight: 700 },
      paragraph: { color: 'textPrimary', fontSize: 'md' },
      caption: { color: 'muted', fontSize: 'sm' },
      label: { color: 'textSecondary', fontSize: 'sm', fontWeight: 600 },
      table: { fontSize: 'sm' },
      header: { background: 'surface', color: 'primary' },
      footer: { background: 'surface', color: 'muted' },
      summaryCard: { background: 'surface', color: 'primary' },
      metricCard: { background: 'surface', color: 'textPrimary' },
      divider: { borderColor: 'border' },
      section: {},
    },
  },
  DefaultTheme,
);

