/**
 * sales-report.ts
 *
 * Multi-section sales report with headers, summary cards, and metadata.
 *
 * Run:
 *   pnpm example sales-report
 *
 * Output:
 *   examples/sales-report.pdf
 */

import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Report } from '@reportforge/core';

const outputPath = join(fileURLToPath(import.meta.url), '..', 'sales-report.pdf');

const report = Report.create({
  metadata: {
    title: 'Monthly Sales Report',
    author: 'ReportForge Analytics',
    subject: 'Sales performance summary',
    keywords: ['sales', 'monthly', 'report'],
    pageBackground: '#fafafa',
  },
})
  .header((h) => h.title('Acme Corp').paragraph('Monthly Sales — July 2026'))
  .footer((f) => f.paragraph('Confidential · Generated by ReportForge'))
  .title('Monthly Sales Report')
  .paragraph('Sales increased by 18% this month compared to the previous period.')
  .divider()
  .section((s) => {
    s.subtitle('Highlights');
    s.summaryCard({ label: 'Total Revenue', value: '$482,910', trend: '+18%' });
    s.summaryCard({ label: 'New Customers', value: '214', trend: '+9%' });
    s.paragraph(
      'Growth was strongest in the enterprise segment. Customer retention remained above 94%.',
    );
  })
  .divider()
  .section((s) => {
    s.subtitle('Regional Performance');
    s.paragraph('North America led revenue growth at 22%, followed by EMEA at 14%.');
  });

await report.toPDF(outputPath);

console.log(`✔ PDF written to: ${outputPath}`);
