/**
 * simple-report.ts
 *
 * A more complete ReportForge example demonstrating:
 * - Multiple sections
 * - Headers and footers
 * - Tables (placeholder)
 * - Summary cards (placeholder)
 * - Multi-element layouts
 *
 * Run:
 *   pnpm --filter @reportforge/examples simple-report
 * Output:
 *   simple-report.pdf  (in the examples/ directory)
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Report } from '@reportforge/core';
import { DisplayListGenerator } from '@reportforge/display-list';
import { LayoutEngine } from '@reportforge/layout';
import { PdfRenderer } from '@reportforge/renderer-pdf';

// ─── Build the report ─────────────────────────────────────────────────────────

const report = Report.create({
  title: 'Monthly Sales Report',
  author: 'ReportForge Demo',
  subject: 'Sales performance for Q4 2026',
})
  .header((header) => header.title('ReportForge').paragraph('Monthly Sales Report — Q4 2026'))
  .footer((footer) => footer.paragraph('Confidential · Generated by ReportForge · Page 1'))
  .title('Monthly Sales Report')
  .paragraph(
    'This report summarises the sales performance for Q4 2026. ' +
      'All figures are in USD. Data is sourced from the internal CRM system.',
  )
  .divider()
  .section((executive) => {
    executive.subtitle('Executive Summary');
    executive.summaryCard({ label: 'Total Revenue', value: '$3,847,291', trend: '+12%' });
    executive.summaryCard({ label: 'New Customers', value: '1,204', trend: '+8%' });
    executive.summaryCard({ label: 'Avg Deal Size', value: '$3,196', trend: '-2%' });
    executive.paragraph(
      'Revenue grew 12% year-over-year, driven by strong performance in the ' +
        'Enterprise segment. New customer acquisition accelerated in Q4 following ' +
        'the launch of the new Partner Programme.',
    );
  })
  .divider()
  .section((detailSection) => {
    detailSection.subtitle('Revenue by Product Line');
    detailSection.table({
      columns: [
        { key: 'product', label: 'Product' },
        { key: 'q4Revenue', label: 'Q4 Revenue' },
        { key: 'yoyGrowth', label: 'YoY Growth' },
        { key: 'margin', label: 'Margin' },
      ],
      rows: [
        { product: 'Enterprise Suite', q4Revenue: '$2,104,000', yoyGrowth: '+18%', margin: '74%' },
        { product: 'Professional', q4Revenue: '$1,021,000', yoyGrowth: '+7%', margin: '68%' },
        { product: 'Starter', q4Revenue: '$512,000', yoyGrowth: '+4%', margin: '61%' },
        { product: 'Add-ons & Services', q4Revenue: '$210,291', yoyGrowth: '+31%', margin: '82%' },
      ],
    });
  })
  .divider()
  .section((chartsSection) => {
    chartsSection.subtitle('Revenue Trend (2024–2026)');
    chartsSection.chart({ title: 'Quarterly Revenue', type: 'bar' });
    chartsSection.paragraph(
      'The chart above shows quarterly revenue from 2024 through 2026. ' +
        'Growth has been consistent, with acceleration in Q3 and Q4 2026.',
    );
  })
  .divider()
  .section((outlookSection) => {
    outlookSection.subtitle('2027 Outlook');
    outlookSection.paragraph(
      'We project continued growth in all product lines, with the Enterprise ' +
        'segment expected to exceed $10M ARR by Q2 2027. The Partner Programme ' +
        'is forecast to contribute 20% of new pipeline.',
    );
    outlookSection.paragraph(
      'Key initiatives for Q1 2027: launch of the new Analytics module, ' +
        'expansion into the APAC market, and the annual user conference.',
    );
  });

// ─── Pipeline ─────────────────────────────────────────────────────────────────

const layoutEngine = new LayoutEngine();
const layout = layoutEngine.layout(report);

const generator = new DisplayListGenerator();
const displayList = generator.generate(layout);

const renderer = new PdfRenderer();
const result = await renderer.renderWithDiagnostics(displayList, {
  title: 'Monthly Sales Report',
  author: 'ReportForge Demo',
  subject: 'Q4 2026 Sales Performance',
  keywords: ['sales', 'revenue', 'Q4', '2026'],
  creator: 'ReportForge Example',
});

// ─── Output ───────────────────────────────────────────────────────────────────

const outputPath = join(fileURLToPath(import.meta.url), '..', 'simple-report.pdf');
writeFileSync(outputPath, result.bytes);

console.log(`✔ PDF written to: ${outputPath}`);
console.log(`  Pages:    ${result.pageCount.toString()}`);
console.log(`  Commands: ${result.commandCount.toString()}`);
console.log(`  Size:     ${(result.bytes.length / 1024).toFixed(1)} KB`);

if (result.warnings.length > 0) {
  console.log(`\n⚠ Warnings (${result.warnings.length.toString()}):`);
  for (const warning of result.warnings) {
    console.log(`  · ${warning}`);
  }
}
