import type { BrandingConfig, TemplateOptions, TemplateValidationIssue, TemplateValidationResult } from './types.js';

export const DEFAULT_BRANDING: BrandingConfig = {
  companyName: 'Your Company',
  primaryColor: '#1a1a2e',
  secondaryColor: '#555555',
  fontFamily: 'Helvetica',
  footerText: 'Generated by ReportForge',
};

export function mergeBranding(
  defaults: Partial<BrandingConfig> | undefined,
  dataBranding: Partial<BrandingConfig> | undefined,
  _options?: TemplateOptions,
): BrandingConfig {
  return {
    ...DEFAULT_BRANDING,
    ...defaults,
    ...dataBranding,
  };
}

export function validateBranding(branding: BrandingConfig): TemplateValidationResult {
  const errors: TemplateValidationIssue[] = [];

  if (branding.companyName.trim().length === 0) {
    errors.push({ message: 'Company name is required for branding.', path: 'branding.companyName' });
  }

  if (branding.logoSrc !== undefined && branding.logoSrc.trim().length === 0) {
    errors.push({ message: 'Logo source must be a non-empty string.', path: 'branding.logoSrc' });
  }

  if (branding.primaryColor !== undefined && !/^#[0-9a-fA-F]{6}$/.test(branding.primaryColor)) {
    errors.push({ message: 'Primary color must be a hex color.', path: 'branding.primaryColor' });
  }

  if (optionsHasUnknownBrandingKeys(branding)) {
    errors.push({ message: 'Invalid branding configuration.', path: 'branding' });
  }

  return { valid: errors.length === 0, errors };
}

function optionsHasUnknownBrandingKeys(_branding: BrandingConfig): boolean {
  return false;
}

/** Watermark placeholder — rendering deferred to a future milestone. */
export function watermarkPlaceholderEnabled(options: TemplateOptions): boolean {
  return options.watermark === true;
}
